In [1]:
import pandas as pd

In [69]:
df_jjj = pd.read_csv("jjj_data.csv", sep='\t')
df_jjj = df_jjj.reset_index()
df_jjj_rename = df_jjj.copy()
df_jjj_rename["title"] = df_jjj_rename["title"].str.replace(".","")
df_jjj_rename["title"] = df_jjj_rename["title"].str.replace("(","")
df_jjj_rename["title"] = df_jjj_rename["title"].str.replace(")","")
df_jjj_rename["title"] = df_jjj_rename["title"].str.replace("'","")
df_jjj_rename["title"] = df_jjj_rename["title"].str.replace(" ","")
df_jjj_rename["title"] = df_jjj_rename["title"].str.replace(",","")
df_jjj_rename["title"] = df_jjj_rename["title"].str.upper()

df_jjj_rename

,index,year,title,artist,duration,country
0,0,1993,ASSHOLE,Denis Leary,4:26,USA
1,1,1993,CREEP,Radiohead,3:56,England
2,2,1993,LINGER,The Cranberries,4:35,Ireland
3,3,1993,NORAIN,Blind Melon,3:37,USA
4,4,1993,CANNONBALL,The Breeders,3:34,USA
...,...,...,...,...,...,...
2496,2496,2017,CHASIN,Cub Sport,3:11,Australia
2497,2497,2017,LOYALTYFEATRIHANNA,Kendrick Lamar,3:47,USA
2498,2498,2017,SNOW,Angus & Julia Stone,4:12,Australia
2499,2499,2017,ARTYBOYFEATEMMALOUISE,Flight Facilities,3:52,Australia
2500,2500,2017,DONTLEAVE,Snakehips & MØ,3:35,England

In [70]:
df_spotify = pd.read_csv("spotify_data.csv")
df_spotify.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,['Dennis Day'],0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339
3,0.1650,1921,0.967,['Frank Parker'],0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,0.2530,1921,0.957,['Phil Regan'],0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.0380,101.665

In [67]:
df_spotify = df_spotify.reset_index()

In [68]:
df_spotify_rename = df_spotify.copy()
df_spotify_rename["name"] = df_spotify_rename["name"].str.replace(".","")
df_spotify_rename["name"] = df_spotify_rename["name"].str.replace("(","")
df_spotify_rename["name"] = df_spotify_rename["name"].str.replace(")","")
df_spotify_rename["name"] = df_spotify_rename["name"].str.replace("'","")
df_spotify_rename["name"] = df_spotify_rename["name"].str.replace(" ","")
df_spotify_rename["name"] = df_spotify_rename["name"].str.upper()

#df_spotify["artists"] = df_spotify["artists"].str.strip("[]")
#df_spotify["artists"] = df_spotify["artists"].str.strip("'")
#df_spotify["artists"] = df_spotify["artists"].str.replace("'","")
#df_spotify["artists"] = df_spotify["artists"].str.replace(",","")
#df_spotify["artists"] = df_spotify["artists"].str.replace(" ","")
df_spotify_rename

,index,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0,0.0594,1921,0.98200,SergeiRachmaninoffJamesLevineBerlinerPhilharmo...,0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.6650,-20.096,1,"PIANOCONCERTONO3INDMINOR,OP30:IIIFINALEALLABREVE",4,1921,0.0366,80.954
1,1,0.9630,1921,0.73200,DennisDay,0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.1600,-12.441,1,CLANCYLOWEREDTHEBOOM,5,1921,0.4150,60.936
2,2,0.0394,1921,0.96100,KHPKridhamardawaKaratonNgayogyakartaHadiningrat,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.1010,-14.850,1,GATIBALI,5,1921,0.0339,110.339
3,3,0.1650,1921,0.96700,FrankParker,0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.3810,-9.316,1,DANNYBOY,3,1921,0.0354,100.109
4,4,0.2530,1921,0.95700,PhilRegan,0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.2290,-10.096,1,WHENIRISHEYESARESMILING,2,1921,0.0380,101.665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170648,170648,0.6080,2020,0.08460,AnuelAADaddyYankeeKAROLGOzunaJBalvin,0.786,301714,0.808,0,0KkIkfsLEJbrcIhYsCL7L5,0.000289,7,0.0822,-3.702,1,CHINA,72,2020-05-29,0.0881,105.029
170649,170649,0.7340,2020,0.20600,Ashnikko,0.717,150654,0.753,0,0OStKKAuXlxA0fMH54Qs6E,0.000000,7,0.1010,-6.020,1,HALLOWEENIEIII:SEVENDAYS,68,2020-10-23,0.0605,137.936
170650,170650,0.6370,2020,0.10100,MAMAMOO,0.634,211280,0.858,0,4BZXVFYCb76Q0Klojq4piV,0.000009,4,0.2580,-2.226,0,AYA,76,2020-11-03,0.0809,91.688
170651,170651,0.1950,2020,0.00998,Eminem,0.671,337147,0.623,1,5SiZJoLXp3WOl3J4C8IK0d,0.000008,2,0.6430,-7.161,1,DARKNESS,70,2020-01-17,0.3080,75.055
170652,170652,0.6420,2020,0.13200,KEVVOJBalvin,0.856,189507,0.721,1,7HmnJHfs0BkFzX4x8j0hkl,0.004710,7,0.1820,-4.928,1,BILLETESAZULESWITHJBALVIN,74,2020-10-16,0.1080,94.991

In [72]:
df = df_jjj_rename.merge(df_spotify_rename, left_on=["title"], right_on=["name"], how="left")
index_df = df.loc[(df["year_x"] >= df["year_y"]) & (df["year_x"] - df["year_y"] <=3)]
index_df

,index_x,year_x,title,artist,duration,country,index_y,valence,year_y,acousticness,...,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0,1993,ASSHOLE,Denis Leary,4:26,USA,51827.0,0.649,1993.0,0.55400,...,0.000000,2.0,0.154,-10.652,1.0,ASSHOLE,49.0,1993-01-01,0.2490,172.866
3,1,1993,CREEP,Radiohead,3:56,England,14206.0,0.104,1993.0,0.01020,...,0.000141,7.0,0.129,-9.935,1.0,CREEP,82.0,1993-02-22,0.0369,91.841
6,1,1993,CREEP,Radiohead,3:56,England,103206.0,0.126,1992.0,0.00563,...,0.000473,7.0,0.115,-13.057,1.0,CREEP,45.0,1992-09-21,0.0350,91.834
8,2,1993,LINGER,The Cranberries,4:35,Ireland,14213.0,0.204,1993.0,0.07830,...,0.000049,7.0,0.140,-14.918,1.0,LINGER,76.0,1993-03-01,0.0265,94.845
10,3,1993,NORAIN,Blind Melon,3:37,USA,14009.0,0.566,1992.0,0.61900,...,0.000051,9.0,0.255,-9.342,1.0,NORAIN,74.0,1992-01-01,0.0316,148.117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5388,2492,2017,LOVEFEATZACARI,Kendrick Lamar,3:33,USA,19024.0,0.779,2017.0,0.26400,...,0.000000,10.0,0.153,-7.343,1.0,LOVEFEATZACARI,79.0,2017-04-14,0.0924,126.058
5392,2495,2017,MASKOFF,Future,3:24,USA,19078.0,0.281,2017.0,0.01020,...,0.021900,2.0,0.165,-8.795,1.0,MASKOFF,80.0,2017-06-30,0.4310,150.062
5394,2497,2017,LOYALTYFEATRIHANNA,Kendrick Lamar,3:47,USA,37843.0,0.419,2017.0,0.02650,...,0.000000,9.0,0.200,-8.983,0.0,LOYALTYFEATRIHANNA,71.0,2017-04-14,0.0573,110.684
5396,2498,2017,SNOW,Angus & Julia Stone,4:12,Australia,124069.0,0.409,2016.0,0.31600,...,0.000000,8.0,0.112,-5.724,1.0,SNOW,56.0,2016-04-08,0.0292,149.950
5399,2500,2017,DONTLEAVE,Snakehips & MØ,3:35,England,91761.0,0.338,2017.0,0.22200,...,0.000000,1.0,0.256,-3.402,1.0,DONTLEAVE,65.0,2017-01-06,0.0753,122.381

In [74]:
index = index_df[["index_x"]].drop_duplicates(keep="first")
index
#df.loc[df["valence"].isna()]

      index_x
0           0
3           1
8           2
10          3
12          4
...       ...
5388     2492
5392     2495
5394     2497
5396     2498
5399     2500

[1010 rows x 1 columns]

In [76]:
df_jjj.loc[df_jjj["index"].isin(index["index_x"])]

,index,year,title,artist,duration,country
0,0,1993,Asshole,Denis Leary,4:26,USA
1,1,1993,Creep,Radiohead,3:56,England
2,2,1993,Linger,The Cranberries,4:35,Ireland
3,3,1993,No Rain,Blind Melon,3:37,USA
4,4,1993,Cannonball,The Breeders,3:34,USA
...,...,...,...,...,...,...
2492,2492,2017,LOVE. (feat. Zacari),Kendrick Lamar,3:33,USA
2495,2495,2017,Mask Off,Future,3:24,USA
2497,2497,2017,LOYALTY. (feat. Rihanna),Kendrick Lamar,3:47,USA
2498,2498,2017,Snow,Angus & Julia Stone,4:12,Australia
2500,2500,2017,Don't Leave,Snakehips & MØ,3:35,England