In [1]:
import pandas as pd
import re

In [2]:
df_jjj = pd.read_csv("../Resource/jjj_data.csv", sep='\t')
df_jjj = df_jjj.reset_index()
df_jjj_rename = df_jjj.copy()

# define how many letters to search
search_len = 6

# use regex to leave all letters only
regex = re.compile('[^a-zA-Z]')

df_jjj_rename["title"] = df_jjj_rename.apply(lambda x: regex.sub("", x.title), axis=1)
df_jjj_rename["title"] = df_jjj_rename["title"].str.upper()

df_jjj_rename["artist"] = df_jjj_rename.apply(lambda x: regex.sub("", x.artist), axis=1)
df_jjj_rename["artist"] = df_jjj_rename["artist"].str.upper()

# get the left {search_len} chars, for less than {search_len}, pad some '.' at right
df_jjj_rename["artist_s"] = df_jjj_rename["artist"].str[:search_len].str.pad(search_len, side="right", fillchar=".")
df_jjj_rename["title_s"] = df_jjj_rename["title"].str[:search_len].str.pad(search_len, side="right", fillchar=".")

df_jjj_rename

,index,year,title,artist,duration,country,artist_s,title_s
0,0,1993,ASSHOLE,DENISLEARY,4:26,USA,DENISL,ASSHOL
1,1,1993,CREEP,RADIOHEAD,3:56,England,RADIOH,CREEP.
2,2,1993,LINGER,THECRANBERRIES,4:35,Ireland,THECRA,LINGER
3,3,1993,NORAIN,BLINDMELON,3:37,USA,BLINDM,NORAIN
4,4,1993,CANNONBALL,THEBREEDERS,3:34,USA,THEBRE,CANNON
...,...,...,...,...,...,...,...,...
2496,2496,2017,CHASIN,CUBSPORT,3:11,Australia,CUBSPO,CHASIN
2497,2497,2017,LOYALTYFEATRIHANNA,KENDRICKLAMAR,3:47,USA,KENDRI,LOYALT
2498,2498,2017,SNOW,ANGUSJULIASTONE,4:12,Australia,ANGUSJ,SNOW..
2499,2499,2017,ARTYBOYFEATEMMALOUISE,FLIGHTFACILITIES,3:52,Australia,FLIGHT,ARTYBO
2500,2500,2017,DONTLEAVE,SNAKEHIPSM,3:35,England,SNAKEH,DONTLE

In [3]:
df_spotify = pd.read_csv("../Resource/spotify_data.csv")
df_spotify = df_spotify.reset_index()
df_spotify.head()

,index,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,1,0.9630,1921,0.732,['Dennis Day'],0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339
3,3,0.1650,1921,0.967,['Frank Parker'],0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,4,0.2530,1921,0.957,['Phil Regan'],0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.0380,101.665

In [4]:
# do the samething as df_jjj_rename
df_spotify_rename = df_spotify.copy()

err_index = []

# df_spotify_rename["name"] = df_spotify_rename.apply(lambda x: regex.sub("", x.name), axis=1)
# use above line with trigger exception, have no idea why 

for index, row in df_spotify_rename.iterrows():
    try:
        df_spotify_rename.at[index, "name"] = regex.sub("", df_spotify_rename.at[index, "name"])
    except:
        err_index.append(index)

df_spotify_rename["name"] = df_spotify_rename["name"].str.upper()

df_spotify_rename["artists"] = df_spotify_rename.apply(lambda x: regex.sub("", x.artists), axis=1)
df_spotify_rename["artists"] = df_spotify_rename["artists"].str.upper()

df_spotify_rename["name_s"] = df_spotify_rename["name"].str[:search_len].str.pad(search_len, side="right", fillchar=".")
df_spotify_rename["artists_s"] = df_spotify_rename["artists"].str[:search_len].str.pad(search_len, side="right", fillchar=".")

In [5]:
df_spotify_rename

,index,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,...,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo,name_s,artists_s
0,0,0.0594,1921,0.98200,SERGEIRACHMANINOFFJAMESLEVINEBERLINERPHILHARMO...,0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,...,0.6650,-20.096,1,PIANOCONCERTONOINDMINOROPIIIFINALEALLABREVE,4,1921,0.0366,80.954,PIANOC,SERGEI
1,1,0.9630,1921,0.73200,DENNISDAY,0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,...,0.1600,-12.441,1,CLANCYLOWEREDTHEBOOM,5,1921,0.4150,60.936,CLANCY,DENNIS
2,2,0.0394,1921,0.96100,KHPKRIDHAMARDAWAKARATONNGAYOGYAKARTAHADININGRAT,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,...,0.1010,-14.850,1,GATIBALI,5,1921,0.0339,110.339,GATIBA,KHPKRI
3,3,0.1650,1921,0.96700,FRANKPARKER,0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,...,0.3810,-9.316,1,DANNYBOY,3,1921,0.0354,100.109,DANNYB,FRANKP
4,4,0.2530,1921,0.95700,PHILREGAN,0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,...,0.2290,-10.096,1,WHENIRISHEYESARESMILING,2,1921,0.0380,101.665,WHENIR,PHILRE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170648,170648,0.6080,2020,0.08460,ANUELAADADDYYANKEEKAROLGOZUNAJBALVIN,0.786,301714,0.808,0,0KkIkfsLEJbrcIhYsCL7L5,...,0.0822,-3.702,1,CHINA,72,2020-05-29,0.0881,105.029,CHINA.,ANUELA
170649,170649,0.7340,2020,0.20600,ASHNIKKO,0.717,150654,0.753,0,0OStKKAuXlxA0fMH54Qs6E,...,0.1010,-6.020,1,HALLOWEENIEIIISEVENDAYS,68,2020-10-23,0.0605,137.936,HALLOW,ASHNIK
170650,170650,0.6370,2020,0.10100,MAMAMOO,0.634,211280,0.858,0,4BZXVFYCb76Q0Klojq4piV,...,0.2580,-2.226,0,AYA,76,2020-11-03,0.0809,91.688,AYA...,MAMAMO
170651,170651,0.1950,2020,0.00998,EMINEM,0.671,337147,0.623,1,5SiZJoLXp3WOl3J4C8IK0d,...,0.6430,-7.161,1,DARKNESS,70,2020-01-17,0.3080,75.055,DARKNE,EMINEM
170652,170652,0.6420,2020,0.13200,KEVVOJBALVIN,0.856,189507,0.721,1,7HmnJHfs0BkFzX4x8j0hkl,...,0.1820,-4.928,1,BILLETESAZULESWITHJBALVIN,74,2020-10-16,0.1080,94.991,BILLET,KEVVOJ

In [6]:
# merge by ["title_4","artist_4"] and ["name_4", "artists_4"]
df_title_artist = df_jjj_rename.merge(df_spotify_rename, left_on=["title_s","artist_s"], right_on=["name_s", "artists_s"], how="inner")

# merge by "title_4" only
df_title_only = df_jjj_rename.merge(df_spotify_rename, left_on=["title_s"], right_on=["name_s"], how="inner")

# choose one of the above for later processing
index_df_good = df_title_artist[["index_x","index_y", "year_x","year_y", "title", "name", "title_s", "name_s", "artist", "artists", "artist_s", "artists_s"]]
# index_df_good = df_title_artist[["index_x","index_y", "year_x","year_y", "title", "name", "title_4", "name_4", "artist", "artists"]]

# filter by year compare (results less than merge by ["title_4","artist_4"] and ["name_4", "artists_4"])
# df_title_artist_year = df_title_artist.loc[(df_title_artist["year_x"] >= df_title_artist["year_y"]) & (df_title_artist["year_x"] - df_title_artist["year_y"] <=10)]
# index_df_good = df_title_artist_year[["index_x","index_y", "year_x","year_y", "title", "name", "title_4", "name_4", "artist", "artists"]]

#index_df_good
index_df_good

,index_x,index_y,year_x,year_y,title,name,title_s,name_s,artist,artists,artist_s,artists_s
0,0,51827,1993,1993,ASSHOLE,ASSHOLE,ASSHOL,ASSHOL,DENISLEARY,DENISLEARY,DENISL,DENISL
1,1,14206,1993,1993,CREEP,CREEP,CREEP.,CREEP.,RADIOHEAD,RADIOHEAD,RADIOH,RADIOH
2,1,103206,1993,1992,CREEP,CREEP,CREEP.,CREEP.,RADIOHEAD,RADIOHEAD,RADIOH,RADIOH
3,2,14213,1993,1993,LINGER,LINGER,LINGER,LINGER,THECRANBERRIES,THECRANBERRIES,THECRA,THECRA
4,2,121243,1993,2002,LINGER,LINGER,LINGER,LINGER,THECRANBERRIES,THECRANBERRIES,THECRA,THECRA
...,...,...,...,...,...,...,...,...,...,...,...,...
1406,2495,19078,2017,2017,MASKOFF,MASKOFF,MASKOF,MASKOF,FUTURE,FUTURE,FUTURE,FUTURE
1407,2495,91745,2017,2017,MASKOFF,MASKOFFFEATKENDRICKLAMARREMIX,MASKOF,MASKOF,FUTURE,FUTUREKENDRICKLAMAR,FUTURE,FUTURE
1408,2495,140196,2017,2017,MASKOFF,MASKOFFMARSHMELLOREMIX,MASKOF,MASKOF,FUTURE,FUTUREMARSHMELLO,FUTURE,FUTURE
1409,2497,37843,2017,2017,LOYALTYFEATRIHANNA,LOYALTYFEATRIHANNA,LOYALT,LOYALT,KENDRICKLAMAR,KENDRICKLAMARRIHANNA,KENDRI,KENDRI
1410,2500,91761,2017,2017,DONTLEAVE,DONTLEAVE,DONTLE,DONTLE,SNAKEHIPSM,SNAKEHIPSM,SNAKEH,SNAKEH

In [7]:
# get the jjj unique index in the merged dataframe
index_jjj = index_df_good.drop_duplicates(subset=["index_x"], keep="first")
index_jjj


final_df = index_jjj[["index_x","index_y"]]
final_df = final_df.merge(df_jjj, left_on="index_x", right_on="index", how="inner")
final_df = final_df.merge(df_spotify, left_on="index_y", right_on="index", how="inner")
final_df = final_df.drop(columns=["index_x", "index_y"])

final_df

,year_x,title,artist,duration,country,valence,year_y,acousticness,artists,danceability,...,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,1993,Asshole,Denis Leary,4:26,USA,0.649,1993,0.55400,['Denis Leary'],0.378,...,0.000000,2,0.154,-10.652,1,Asshole,49,1993-01-01,0.2490,172.866
1,1993,Creep,Radiohead,3:56,England,0.104,1993,0.01020,['Radiohead'],0.515,...,0.000141,7,0.129,-9.935,1,Creep,82,1993-02-22,0.0369,91.841
2,1993,Linger,The Cranberries,4:35,Ireland,0.204,1993,0.07830,['The Cranberries'],0.439,...,0.000049,7,0.140,-14.918,1,Linger,76,1993-03-01,0.0265,94.845
3,1993,No Rain,Blind Melon,3:37,USA,0.566,1992,0.61900,['Blind Melon'],0.389,...,0.000051,9,0.255,-9.342,1,No Rain,74,1992-01-01,0.0316,148.117
4,1993,Cannonball,The Breeders,3:34,USA,0.729,1993,0.00915,['The Breeders'],0.502,...,0.783000,3,0.284,-9.760,1,Cannonball,65,1993-08-30,0.0407,112.508
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1096,2017,The Way You Used To Do,Queens Of The Stone Age,4:34,USA,0.433,2017,0.01020,['Queens of the Stone Age'],0.474,...,0.104000,0,0.362,-5.909,1,The Way You Used to Do,63,2017-08-25,0.2720,97.691
1097,2017,LOVE. (feat. Zacari),Kendrick Lamar,3:33,USA,0.779,2017,0.26400,"['Kendrick Lamar', 'Zacari']",0.800,...,0.000000,10,0.153,-7.343,1,LOVE. FEAT. ZACARI.,79,2017-04-14,0.0924,126.058
1098,2017,Mask Off,Future,3:24,USA,0.281,2017,0.01020,['Future'],0.833,...,0.021900,2,0.165,-8.795,1,Mask Off,80,2017-06-30,0.4310,150.062
1099,2017,LOYALTY. (feat. Rihanna),Kendrick Lamar,3:47,USA,0.419,2017,0.02650,"['Kendrick Lamar', 'Rihanna']",0.658,...,0.000000,9,0.200,-8.983,0,LOYALTY. FEAT. RIHANNA.,71,2017-04-14,0.0573,110.684
1100,2017,Don't Leave,Snakehips & MÃ˜,3:35,England,0.338,2017,0.22200,"['Snakehips', 'MÃ˜']",0.657,...,0.000000,1,0.256,-3.402,1,Don't Leave,65,2017-01-06,0.0753,122.381